common:
  containerRegistryURL: mahadevdevops.azurecr.io
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:mahadevsql.database.windows.net,1433;Database=mahadev;Uid=SQLUser;Pwd=MahadevJi@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

ui:
  replicas: 2
  image:
    name: todo-ui
    tag: v2
  ingress:
    host: qa-ui.shruti.online
  env:
    REACT_APP_GET_TASKS_API_BASE_URL: "http://qa-get-tasks-api.shruti.online"
    REACT_APP_DELETE_TASK_API_BASE_URL: "http://qa-delete-task-api.shruti.online"
    REACT_APP_CREATE_TASK_API_BASE_URL: "http://qa-add-task-api.shruti.online"

addTask:
  replicas: 1
  image:
    name: todo-add-tasks-api
    tag: v1
  ingress:
    host: qa-add-task-api.shruti.online

deleteTask:
  replicas: 2
  image:
    name: todo-delete-tasks-api
    tag: v1
  ingress:
    host: qa-delete-task-api.shruti.online

getTask:
  replicas: 1
  image:
    name: todo-get-tasks-api
    tag: v1
  ingress:
    host: qa-get-tasks-api.shruti.online
